import streamlit as st
import yfinance as yf
import pandas as pd
import ta

# Streamlit UI
st.title("Crypto Technical Analysis Signals")
st.sidebar.header("Settings")

# User selects ticker
ticker = st.sidebar.text_input("Enter Crypto Ticker (e.g., BTC-USD)", "BTC-USD")

# User inputs for indicators
sma_short = st.sidebar.slider("SMA Short Period", 10, 100, 50)
sma_long = st.sidebar.slider("SMA Long Period", 100, 400, 200)
bb_period = st.sidebar.slider("Bollinger Bands Period", 10, 50, 20)
rsi_period = st.sidebar.slider("RSI Period", 10, 30, 14)
macd_fast = st.sidebar.slider("MACD Fast Period", 5, 20, 12)
macd_slow = st.sidebar.slider("MACD Slow Period", 20, 50, 26)
macd_signal = st.sidebar.slider("MACD Signal Period", 5, 20, 9)

# Fetch crypto data
data = yf.download(ticker, period="6mo", interval="1d")

# Check if data is loaded correctly
if data.empty:
    st.error("Failed to load data. Try again later.")
    st.stop()

# Ensure 'Close' column exists and has valid data
if "Close" not in data.columns or data["Close"].dropna().empty:
    st.error("No valid 'Close' price data found. Try another ticker.")
    st.write("Downloaded data preview:")
    st.write(data.head())  # Display raw data for debugging
    st.stop()

# Handle missing values
data["Close"].fillna(method="ffill", inplace=True)
close_series = data["Close"].astype(float).squeeze()

# Calculate Indicators using 'ta' library
try:
    data["SMA_S"] = ta.trend.SMAIndicator(close_series, window=sma_short).sma_indicator()
    data["SMA_L"] = ta.trend.SMAIndicator(close_series, window=sma_long).sma_indicator()
    data["RSI"] = ta.momentum.RSIIndicator(close_series, window=rsi_period).rsi()

    # Bollinger Bands
    bbands = ta.volatility.BollingerBands(close_series, window=bb_period)
    data["Upper_BB"] = bbands.bollinger_hband()
    data["Lower_BB"] = bbands.bollinger_lband()

    # MACD
    macd = ta.trend.MACD(close_series, window_slow=macd_slow, window_fast=macd_fast, window_sign=macd_signal)
    data["MACD"] = macd.macd()
    data["MACD_Signal"] = macd.macd_signal()
except Exception as e:
    st.error(f"Error calculating indicators: {e}")
    st.write("Data preview:")
    st.write(data.head())  # Debugging output
    st.stop()

# Drop NaN values generated by indicators
data.dropna(inplace=True)

# Ensure there's enough data to calculate signals
if len(data) < 2:
    st.error("Not enough historical data to generate signals.")
    st.stop()

# Get latest data
latest = data.iloc[-1]
prev = data.iloc[-2]

# Signal detection logic
signals = []

# SMA Crossovers
if prev["SMA_S"] < prev["SMA_L"] and latest["SMA_S"] > latest["SMA_L"]:
    signals.append("Golden Cross: SMA Short crossed above SMA Long (Bullish)")

if prev["SMA_S"] > prev["SMA_L"] and latest["SMA_S"] < latest["SMA_L"]:
    signals.append("Death Cross: SMA Short crossed below SMA Long (Bearish)")

# RSI Conditions
if latest["RSI"] > 70:
    signals.append("RSI Overbought: Potential price reversal downward")

if latest["RSI"] < 30:
    signals.append("RSI Oversold: Potential price reversal upward")

# Bollinger Bands
if latest["Close"] > latest["Upper_BB"]:
    signals.append("Price Above Upper Bollinger Band: Market may be overbought")

if latest["Close"] < latest["Lower_BB"]:
    signals.append("Price Below Lower Bollinger Band: Market may be oversold")

# MACD Crossovers
if prev["MACD"] < prev["MACD_Signal"] and latest["MACD"] > latest["MACD_Signal"]:
    signals.append("Bullish MACD Crossover: MACD crossed above Signal Line (Buy Signal)")

if prev["MACD"] > prev["MACD_Signal"] and latest["MACD"] < latest["MACD_Signal"]:
    signals.append("Bearish MACD Crossover: MACD crossed below Signal Line (Sell Signal)")

# Display signals in the dashboard
st.subheader(f"Latest Signals for {ticker}")
if signals:
    for signal in signals:
        st.write(f"✅ {signal}")
else:
    st.write("🔍 No significant signals detected.")
